"""Read-only VietShare v1 adapter with no built-in network transport."""

from nyan_shop_bot.suppliers.vietshare.adapter import (
    VIETSHARE_CAPABILITIES,
    Clock,
    NonceSource,
    RetrySleeper,
    VietShareReadAdapter,
    VietShareTransport,
    parse_retry_after,
)
from nyan_shop_bot.suppliers.vietshare.models import (
    ProductListError,
    ProductListErrorCode,
    ProductListOutcome,
    ProductListRateLimited,
    ProductListSuccess,
    ProductListTimeout,
    ResponseValidationError,
    SensitiveHeaders,
    UnsupportedRead,
    UnsupportedReadOperation,
    VietShareConfigurationError,
    VietShareCredentials,
    VietShareProduct,
    VietShareProductList,
    VietShareRequest,
    VietShareResponse,
    VndMoney,
    parse_product_list,
)
from nyan_shop_bot.suppliers.vietshare.signing import (
    PRODUCTION_BASE_URL,
    RequestTarget,
    body_sha256,
    build_request_target,
    build_signed_read_request,
    canonical_string,
    sign_request,
)

__all__ = [
    "PRODUCTION_BASE_URL",
    "VIETSHARE_CAPABILITIES",
    "Clock",
    "NonceSource",
    "ProductListError",
    "ProductListErrorCode",
    "ProductListOutcome",
    "ProductListRateLimited",
    "ProductListSuccess",
    "ProductListTimeout",
    "RequestTarget",
    "ResponseValidationError",
    "RetrySleeper",
    "SensitiveHeaders",
    "UnsupportedRead",
    "UnsupportedReadOperation",
    "VietShareConfigurationError",
    "VietShareCredentials",
    "VietShareProduct",
    "VietShareProductList",
    "VietShareReadAdapter",
    "VietShareRequest",
    "VietShareResponse",
    "VietShareTransport",
    "VndMoney",
    "body_sha256",
    "build_request_target",
    "build_signed_read_request",
    "canonical_string",
    "parse_product_list",
    "parse_retry_after",
    "sign_request",
]
